image: "ruby:2.4.1"

# Cache gems in between builds (Disabled)
# cache:
#   paths:
# - vendor/bundle

before_script:
  - ruby -v                                   # Print out ruby version for debugging
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

stages:
  - compile


Build fluentd:
  stage: compile
  script:
    - bundle exec rake build
    - mv pkg/*gem .
    - GEMFILE_NAME=$(ls *gem)
    - echo FLUENTD_GEM=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/file/$GEMFILE_NAME >> release.env
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - "*gem"
      - release.env
